USE [nhs_ae_warehouse];
GO

IF OBJECT_ID('dbo.Dim_Provider', 'U') IS NULL
BEGIN
    CREATE TABLE dbo.Dim_Provider (
        -- 1. Surrogate key: the real identity, generated by the database
        Provider_Key     INT IDENTITY(1,1) PRIMARY KEY,
        -- 2. Business key: the handle matched on across versions (not unique)
        Org_Code         NVARCHAR(50) NOT NULL,
        -- 3. Watched attributes: a change in either opens a new version
        Parent_Org       NVARCHAR(255) NULL,
        Org_Name         NVARCHAR(255) NOT NULL,
        -- 4. Version span: the stretch this version is valid for
        Valid_From       DATE NOT NULL,
        Valid_To         DATE NOT NULL,
        -- 5. Convenience flag: is this the live version right now
        Is_Current       BIT NOT NULL DEFAULT 1,
        -- 6. Audit columns: why the version exists, and when it was written
        Reason_Status    NVARCHAR(255) NOT NULL,
        Load_Timestamp   DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
        -- 7. Absence tracker: the last month this provider actually appeared
        Last_Seen_Month  DATE NOT NULL
    );
END;
GO

IF NOT EXISTS (
    SELECT 1 FROM sys.indexes
    WHERE name = 'UX_Dim_Provider_Current_OrgCode'
      AND object_id = OBJECT_ID('dbo.Dim_Provider')
)
BEGIN
    CREATE UNIQUE INDEX UX_Dim_Provider_Current_OrgCode
        ON dbo.Dim_Provider (Org_Code)
        WHERE Is_Current = 1;
END;
GO